import { PageHeader } from '@/components/page-header';
import './globals.css';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          'bg-repeat heropattern-hideout-gray-200 bg-gray-200/50'
        )}
      >
        <PageHeader />
        {children}
      </body>
    </html>
  );
}
